### PR TITLE
Update content.toml

### PR DESCRIPTION
**Pull request by 20ashah**
added name to compiler frameworks paper

### CODE REVIEW

**Comment by sampsyo** [comment]
Sounds good, as long as @JohnDRubio agrees!

**Comment by matth2k** [comment]
@20ashah Can you add my name Matthew Hofmann to the MLIR paper? I already tried to get on a different paper.

**Comment by sampsyo** [comment]
Merging this now! @matth2k, if everyone agrees, please open a separate PR.

**Comment by JohnDRubio** [comment]
Adding @matth2k is fine with me!

**Comment by jdroob** [comment]
> Sounds good, as long as @JohnDRubio agrees!

That's fine with me!

**Comment by jdroob** [comment]
> Merging this now! @matth2k, if everyone agrees, please open a separate PR.

Works for me!

**Pull request merged**
