### PR TITLE
Update content.toml

### PR DESCRIPTION
**Pull request by andrewb1999**

### CODE REVIEW

**Comment by sampsyo** [comment]
Yo @ayakayorihiro and @andrewb1999, are you both cool with teaming up for this paper? (If so, please resolve the conflict to include both of your names!)

**Comment by andrewb1999** [comment]
That works with me! If @ayakayorihiro is okay with it too I can go ahead and amend this pull request.

**Comment by ayakayorihiro** [comment]
That sounds great to me, thanks @andrewb1999 !

**Comment by sampsyo** [comment]
Excellent; thanks, y'all!

**Pull request merged**
