### PR TITLE
Update content.toml

### PR DESCRIPTION
**Pull request by hj424**
I would like to lead the discussion for this paper.

Thanks,
Hanchen

### CODE REVIEW

**Comment by sampsyo** [comment]
Sounds great; thanks!

**Comment by hj424** [comment]
I just enrolled in this course today. Could you please add me to the CMS and send me a Zulip invitation? 
Thanks,
Hanchen

**Comment by sampsyo** [comment]
I added you to CMS. There is no Zulip invitation to send; please just follow the link on the homepage.

**Comment by hj424** [comment]
Thanks! I have got into the CMS. But for Zulip, when I click the "sign up for Zulip" link in the course website (https://www.cs.cornell.edu/courses/cs6120/2020fa/). I got this error page: 
image
Then I click the "sign up" and got the following page:
image

**Comment by sampsyo** [comment]
Thanks! I have refreshed the link now, I think.

**Comment by hj424** [comment]
Great, I'm in now, thanks!

**Pull request merged**
